apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-spring-boot
  labels:
    app: tp-spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp-spring-boot
  template:
    metadata:
      labels:
        app: tp-spring-boot
    spec:
      containers:
      - name: tp-spring-boot
        image: tp-spring-boot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        
        # ✅ AJOUTEZ CETTE SECTION
        resources:
          requests:
            memory: "512Mi"    # Mémoire minimale garantie
            cpu: "250m"        # 0.25 CPU garanti
          limits:
            memory: "1Gi"      # Mémoire maximale autorisée
            cpu: "500m"        # 0.5 CPU maximum
        
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5