apiVersion: v1
kind: Service
metadata:
  name: tp-spring-boot-service
  labels:
    app: tp-spring-boot
spec:
  type: NodePort
  selector:
    app: tp-spring-boot
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http